# When we push to the 'main' (staging) branch, validate the DAB is correct and deploy to the Staging environment
# The project manager `uv` is used within the Databricks Asset Bundle
name: Bundle Deployment for Staging
permissions:
  contents: read

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  staging:
    concurrency: staging-bundle-job
    runs-on: ubuntu-latest
    environment: staging

    # Get secrets for Databricks
    env:
      DATABRICKS_TOKEN: ${{ secrets.STAGING_WORKSPACE_TOKEN }}

    steps:
      # Setup
      - name: Checkout code
        if: env.DATABRICKS_TOKEN != ''
        uses: actions/checkout@v4
      - name: Set up Databricks CLI
        if: env.DATABRICKS_TOKEN != ''
        uses: databricks/setup-cli@bf82b7a11475ed8d99eaf2920980fd091ca2cb12 # v0.221.1
      - name: Install uv
        if: env.DATABRICKS_TOKEN != ''
        uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86  # v5.4.2

      # Validate
      - name: Validate Bundle for Staging
        id: validate
        if: env.DATABRICKS_TOKEN != ''
        run: databricks bundle validate -t staging --var="cluster_policy_id=${{ vars.STAGING_CLUSTER_POLICY_ID }}"
      
      # Deploy
      - name: Deploy Bundle to Staging
        id: deploy
        if: env.DATABRICKS_TOKEN != ''
        run: databricks bundle deploy -t staging --var="cluster_policy_id=${{ vars.STAGING_CLUSTER_POLICY_ID }}"
